# Generated by Django 6.0.2 on 2026-02-26 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('head_sign', models.CharField(max_length=255)),
                ('direction', models.IntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transit.route')),
            ],
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.CharField(max_length=8)),
                ('departure_time', models.CharField(max_length=8)),
                ('stop_sequence', models.IntegerField()),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transit.stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transit.trip')),
            ],
        ),
    ]
