# Generated by Django 6.0.2 on 2026-03-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0002_trip_stoptime'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='stop_lat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='stop_lon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
