# Generated by Django 6.0.2 on 2026-03-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0003_stop_stop_lat_stop_stop_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='stop_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
