# Generated by Django 6.0.2 on 2026-03-01 10:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0004_stop_stop_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
