# Generated by Django 6.0.2 on 2026-03-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0005_alter_stop_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('sevice_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
