# Generated by Django 6.0.2 on 2026-03-02 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0006_calendar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='sevice_id',
            new_name='service_id',
        ),
    ]
